[Variables]
;colors 1, 2, 3 are generally the brighter colors
;colors 5, 6, 7 are the darker colors (used to contrast colors 1, 2, 3)
;color 4 is the alternative to color 3 (both are generally button colors)
customColor1=15,132,153
customColor2=144,197,9
customColor3=191,3,86
customColor4=242,238,36
customColor5=20,73,82
customColor6=65,82,20
customColor7=70,10,22
;ALL COLORS MUST BE ENTERED IN "RED,GREEN,BLUE" FORMAT, hexadecimal or web-style color codes will not work due to the use of the alpha channel
